### ISSUE TITLE
specify initial set of opcodes for operations

### ISSUE THREAD

**Issue by drom** [indutny/json-pipeline#2]
I see only `opcode: "add"` in examples and test code. Should we specify some workable set?

**Comment by drom** [comment]
Should we implement node ```type``` as an indication for the behavioral aspects of the opcode, control-flow side effects? Then ```add```, ```sub```, ```xor``` opcodes may share the type, and be treated by compiler in similar manner.

**Comment by indutny** [comment]
@drom the opcodes are implementation-specific. This library provides just a framework. Behavioural aspects are defined by the compiler too.
